luku1 = int(input("anna luku"))
luku2 = int(input("anna luku"))
luku3 = int(input("anna luku"))
summa = (luku1 + luku2 + luku3)
tulo = (luku1 * luku2 * luku3)
keskiarvo = ((luku1 + luku2 + luku3) / 3 )
print(f"summa on {summa} tulo on {tulo} sekä keskiarvo on {keskiarvo}")